breakitdown/config/routes.rb
Rails.application.routes.draw do
  # main
  root 'main#index'
  get 'main/index'

  # guides
  resources :guides
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

breakitdown/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

breakitdown/app/models/block.rb
class Block < ApplicationRecord
  belongs_to :chunk
end

breakitdown/app/models/chunk.rb
class Chunk < ApplicationRecord
  belongs_to :guide
  has_many :blocks, inverse_of: :chunk
  accepts_nested_attributes_for :blocks, :reject_if => :all_blank, :allow_destroy => true

end

breakitdown/app/models/guide.rb
class Guide < ApplicationRecord
  has_many :chunks, inverse_of: :guide
  accepts_nested_attributes_for :chunks, :reject_if => :all_blank, :allow_destroy => true
end

breakitdown/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

breakitdown/app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  def new
    @guide = Guide.new
  end

  def create
    @guide = Guide.new(guide_params)

    if @guide.save
      redirect_to(@guide, :notice => 'Project was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
  end

  def edit
  end

  def destroy
    @guide = Guide.find(params[:id])
    @guide.destroy

    respond_to do |format|
      format.html { redirect_to(guides_url) }
      format.xml  { head :ok }
    end
  end

  def show
    @guide = Guide.find(params[:id])

  end

  def index
    @guides = Guide.all
  end

  private

  def guide_params
    params.require(:guide).permit(:title, :description,
      chunks_attributes: [:id, :_destroy, :title, :description,
        blocks_attributes: [:id, :_destroy, :title, :description]
      ])
  end

end

breakitdown/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

breakitdown/app/helpers/application_helper.rb
module ApplicationHelper
end

breakitdown/app/helpers/guides_helper.rb
module GuidesHelper
end

breakitdown/app/helpers/main_helper.rb
module MainHelper
end

breakitdown/app/views/guides/_block_fields.html.erb
<div class='nested-fields block-fields'>
  <div class="field">
    <%= f.text_field :title, placeholder: "Skill/ Concept" %>
  </div>
  <div class="field">
    <%= f.text_field :description, placeholder: "Description" %>
  </div>
  <%= link_to_remove_association f do %>
    <div class="modal-close">
      <i class="fa fa-times"></i>
    </div>
  <% end %>
</div>

breakitdown/app/views/guides/_chunk_fields.html.erb
<div class='nested-fields chunk-fields'>
  <div class="field">
    <%= f.text_field :title, placeholder: "Title" %>
  </div>
  <div class="field">
    <%= f.text_field :description, placeholder: "Introduction" %>
  </div>
    <%= link_to_remove_association f do %>
      <div class="modal-close">
        <i class="fa fa-times"></i>
      </div>
    <% end %>
  <div class='blocks'>
    <%= f.fields_for :blocks do |block| %>
      <%= render 'block_fields', :f => block %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'add block', f, :blocks %>
    </div>

  </div>
</div>

breakitdown/app/views/guides/create.html.erb
<h1>Guides#create</h1>
<p>Find me in app/views/guides/create.html.erb</p>

breakitdown/app/views/guides/destroy.html.erb
<h1>Guides#destroy</h1>
<p>Find me in app/views/guides/destroy.html.erb</p>

breakitdown/app/views/guides/edit.html.erb
<h1>Guides#edit</h1>
<p>Find me in app/views/guides/edit.html.erb</p>

breakitdown/app/views/guides/index.html.erb
<h1>Guides Index</h1>
<p> Find a study guide that suits your needs </p>
<% @guides.each do |guide| %>
  <%= link_to guide_path(guide.id) do %>
    <div>
      <h2><%= guide.title %></h2>
      <p><%= guide.description %></p>
    </div>
  <% end %>
<% end %>

breakitdown/app/views/guides/new.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>
    <div>
      <h1>Create a Study Guide</h1>
      <p>Break down the topic into fundamental concepts and skills.</p>
      <p>Remember to chunk them up!</p>
    </div>
    <div>
      <%= form_for @guide do |f| %>
        <div class="field">
          <%= f.text_field :title, placeholder: "Topic"%>
        </div>
        <div class="field">
          <%= f.text_area(:description, rows: 4, placeholder: "Intoduce the topic here") %>
        </div>
        <h3>Chunks</h3>
        <div id='chunks'>
          <%= f.fields_for :chunks do |chunk| %>
            <%= render 'chunk_fields', :f => chunk %>
          <% end %>
          <div class='links'>
            <%= link_to_add_association 'add chunk', f, :chunks %>
          </div>
        </div>
        <%= f.submit 'Save' %>
      <% end %>
    </div>

  </body>
</html>

breakitdown/app/views/guides/show.html.erb
<h1><%= @guide.title %></h1>

<p><%= @guide.description %></p>
<p><%= @guide.chunks.count %></p>

<% @guide.chunks.each do |chunk| %>
  <div>
    <h2><%= chunk.title %></h2>
    <p><%= chunk.description %></p>
      <% chunk.blocks.each do |block| %>
        <div>
          <strong><%= block.title %></strong>
          <%= block.description %>
        </div>
      <% end %>
  </div>
<% end %>

breakitdown/app/views/guides/update.html.erb
<h1>Guides#update</h1>
<p>Find me in app/views/guides/update.html.erb</p>

breakitdown/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Breakitdown</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

breakitdown/app/views/main/index.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>
    <div class="content-right">
      <a href="#">Login</a>
    </div>

    <div class="oneline-content">
      <div class="content-center">
        <h1>Hi! What do you want to do today?</h1>
      </div>

      <div class="content-center">
        <div class="btn-focus">
          <%= link_to "Make a Guide", { :controller => :guides, :action => :new }, { class: ""} %>
        </div>
        <div class="btn-focus">
          <%= link_to "Use a Guide", { :controller => :guides, :action => :index }, { class: ""} %>
        </div>
      </div>
    </div>
  </body>
</html>